# Site settings
title: Neurocyte Biosystems
description: 
baseurl: # the subpath of your site, e.g. /blog
url: neurocyte.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Neurocyte Biosystems
#user_description: 
user_title: coming soon
# email: 
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
#linkedin_username: 
# github_username:  
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

